---
resource_types:
- name: semver
  type: registry-image
  source:
    repository: concourse/semver-resource

resources:
- name: app
  type: git
  source:
    uri: git@github.com:clarafu/concourse-demo.git
    branch: master
    private_key: ((app-repo-key))
  icon: github
  public: true

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:clarafu/concourse-demo.git
    branch: version
    file: version
    private_key: ((app-repo-key))
  icon: tag
  public: true

- name: app-pre-release
  type: github-release
  source:
    owner: clarafu
    repository: concourse-demo
    access_token: ((dummy-user-access-token))
    pre_release: true
    release: false
  public: true
  icon: ferry

- name: app-release
  type: github-release
  source:
    owner: clarafu
    repository: concourse-demo
    access_token: ((dummy-user-access-token))
  public: true
  icon: ferry

jobs:
- name: test
  public: true
  plan:
  - get: app
    trigger: true
  - task: test-app
    file: app/ci/tasks/test-app.yml

- name: bump-version
  public: true
  plan:
  - put: version
    params: {bump: major}

- name: build
  public: true
  plan:
  - get: version
  - get: app
    passed: [test]
    trigger: true
  - task: build-app
    file: app/ci/tasks/build-app.yml
  - put: app-pre-release
    params:
      name: version/version
      tag: version/version
      globs:
      - built-app/app

- name: publish
  public: true
  plan:
  - get: version
    passed: [build]
  - get: app-pre-release
    passed: [build]
  - put: app-release
    params:
      name: version/version
      tag: version/version
      globs:
      - app-pre-release/app

